### ISSUE TITLE
List Generator doesn't generate unique values between list items

### ISSUE THREAD

**Issue by wsidl** [wsidl/syntrend#18]
## Summary

For List Generators where a complex object is being used as a sub-type, the object is parsed once and re-used across all other items in the list.

## Affected Version

0.1.1

## Expected Behaviour

A working example using a simple generator sub-type would look like:

```yaml
list:
  type: list
  sub_type:
    type: string
```

and produces a valid result:

```json
["HdSvCg44pAcar6X", "mruSFEK", "AS41qBLLN", "uIOwqWTGsg3x"]
```

But if a complex sub-type is used, each value within the item is re-used.

```yaml
list:
  type: list
  sub_type:
    type: object
    properties:
      item:
        type: string
```

which results in re-used string values

```json
[{"item": "j20EeNbt97NCU"}, {"item": "j20EeNbt97NCU"}, {"item": "j20EeNbt97NCU"}, {"item": "j20EeNbt97NCU"}]
```

## Current Behaviour

The second example above would generate unique values for each item in the list. Something like:

```json
[{"item": "HdSvCg44pAcar6X"}, {"item": "mruSFEK"}, {"item": "AS41qBLLN"}, {"item": "uIOwqWTGsg3x"}]
```
