### ISSUE TITLE
bug: XML Formatter cannot produce multiple documents for an object

### ISSUE THREAD

**Issue by wsidl** [wsidl/syntrend#25]
# Bug Report

**Syntrend Version:** v0.2.0

## Current behavior

XML Formatter produces an error when generating multiple documents (not a collection)

## Expected behavior

Multiple files/XML Documents can be created

## Steps to reproduce

create a project with an xml format with count > 1

## Related Project File

```yaml
output:
  format: xml
  count: 4
type: object
properties:
  prop1:
    type: string
    xml_attr: true
  prop2:
    type: integer
    xml_attr: true
```

## Other information

n/a
