### ISSUE TITLE
bug: Cannot retrieve ref from external file even with provided path

### ISSUE THREAD

**Issue by wsidl** [wsidl/syntrend#30]
# Bug Report

**Syntrend Version:** v0.3.0

## Current behavior

Using two YAML files (in the examples section), one containing the project root with another containing references. Running this project will generate a KeyError:

```
$ syntrend generate project_.yaml
Error Encountered: (KeyError)
  | ('ref', 'obj2')
```

## Expected behavior

Ensure the provided path has been loaded before checking the reference is available.

## Steps to reproduce

- Use above project YAML files
- Run `syntrend generate project.yaml`

## Related Project File

project.yaml:

```yaml
objects:
  obj2:
    bases:
      - path: obj.yaml
        ref: obj2
```

obj.yaml:

```yaml
--- !syntrend/ref::obj2
type: object
properties:
  attr1:
    type: string
```

## Other information

n/a
